baseURL = "https://hello.observer"
title = "hello observer"
# for smart copyright line, leave this blank and check [params.copyright]

theme = "minimus"

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "hello observer"
title404 = "nothing here."

[params.assets]
favicon = "favicon.png"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "uncopyright"
startYear = "2018"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006-01-02"
listDateFormat = "2006-01-02"
hideEntryNavigation = ["page"] # boolean / array of sections
recentPostsLength = 4
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false
homepageSections = ["recent_posts"]

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "-"

[params.social]
email = ""
github = ""
twitter = ""

[params.social.config]
platforms = ["github","twitter","email"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "posts"
weight = -10
identifier = "posts"
url = "/posts"

[blackfriday]
hrefTargetBlank = true

[languages]
[languages.en]
lang = "en"
languageName = "English"
weight = 1
